---
abstract: 'Dependency Injection Container for Perl 5'
author:
  - 'Al Newkirk <awncorp@cpan.org>'
build_requires:
  Data::Object::Class: '2.02'
  Data::Object::ClassHas: '2.01'
  Data::Object::Role::Buildable: '0.03'
  Data::Object::Role::Proxyable: '2.03'
  Data::Object::Space: '2.06'
  JSON::Validator: '3.25'
  Test::Auto: '0.12'
  perl: '5.014'
  routines: '0'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Rewire
requires:
  Data::Object::Class: '2.02'
  Data::Object::ClassHas: '2.01'
  Data::Object::Role::Buildable: '0.03'
  Data::Object::Role::Proxyable: '2.03'
  Data::Object::Space: '2.06'
  JSON::Validator: '3.25'
  perl: '5.014'
  routines: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/iamalnewkirk/rewire/issues
  homepage: https://metacpan.org/pod/Rewire
  repository: git://github.com/iamalnewkirk/rewire.git
version: '0.05'
x_authority: cpan:AWNCORP
x_generated_by_perl: v5.30.1
x_serialization_backend: 'YAML::Tiny version 1.73'
