#!/usr/bin/env perl

use strict;
use warnings;

use feature 'say';

use Data::Dumper::Concise;
use JSON::Validator;
use Mojo::File;

my $jv = JSON::Validator->new;

$jv->schema('file://ruleset.yaml');

my $file = Mojo::File->new('lib/Rewire/Ruleset.pm');

$file->spurt(join ";\n\n", "package Rewire::Ruleset", Dumper $jv->schema->data);
